name: Release

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - run: sudo apt install -y jq
      - run: pnpm i
      - run: pnpm build
      # - name: Set package registry
      # run: npm config set registry https://npm.pkg.github.com
      # - name: Github package registry authentication
      # run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
      - name: Npm registry authentication
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - name: Publish the package to Github and Npm package registries
        run: npm publish --access public --ignore-scripts --@electra.finance:registry='https://registry.npmjs.org'
